version: '3.8'
services:
  web:
    build:
      context: .
      # target: dev
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postreg
      POSTGRES_PASSWORD: postgres
    ports:
      - '5431:5431'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local