version: '3.8'
services:
  web:
    build:
      context: .
      # target: dev
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    # command: "CREATE DATABASE blog"
    expose:
      - 5433
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local
